spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/vjeditor}
spring.datasource.username=${DATABASE_USERNAME:vjeditor}
spring.datasource.password=${DATABASE_PASSWORD:vjeditor}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always