import { Button } from '@/components/ui/Button';
import { useCanvas } from '@/features/editor/CanvasProvider';
import type { AspectRatio } from '@/types';
import { canvasSize } from '@/services/editorService';
import { Layers2, Trash2 } from 'lucide-react';

const ratios: AspectRatio[] = ['16:9', '9:16', '1:1', '4:5'];

export function CanvasProperties() {
  const { state, selected, update, remove, updateSettings, changeLayer } = useCanvas();
  if (!selected) {
    return <aside className="w-[250px] shrink-0 border-l border-border bg-app-elevated p-4 hidden lg:block overflow-auto"><h2 className="text-xs uppercase tracking-wider text-muted">Project</h2><label className="block text-xs text-muted mt-4">Aspect ratio<select value={state.canvas.aspectRatio} onChange={(event) => { const aspectRatio = event.target.value as AspectRatio; updateSettings({ aspectRatio, ...canvasSize(aspectRatio) }); }} className="mt-1 w-full h-8 rounded-lg border border-border bg-panel px-2 text-sm text-fg">{ratios.map((ratio) => <option key={ratio}>{ratio}</option>)}</select></label><label className="block text-xs text-muted mt-3">Canvas background<input type="color" value={state.canvas.background} onChange={(event) => updateSettings({ background: event.target.value })} className="mt-1 h-8 w-full rounded border border-border bg-panel" /></label><div className="flex gap-2 mt-3"><button type="button" onClick={() => updateSettings({ background: '#08090c' })} className="h-6 w-6 rounded bg-black border border-border" aria-label="Black canvas" /><button type="button" onClick={() => updateSettings({ background: '#ffffff' })} className="h-6 w-6 rounded bg-white border border-border" aria-label="White canvas" /></div><label className="block text-xs text-muted mt-3">Zoom<select value={state.canvas.zoom} onChange={(event) => updateSettings({ zoom: Number(event.target.value) })} className="mt-1 w-full h-8 rounded-lg border border-border bg-panel px-2 text-sm text-fg"><option value={50}>50%</option><option value={75}>75%</option><option value={100}>Fit</option><option value={125}>125%</option><option value={150}>150%</option></select></label><p className="text-xs text-muted mt-5">Select a video or image in the Media panel to place it on the canvas.</p></aside>;
  }
  const patch = (key: 'x' | 'y' | 'width' | 'height' | 'rotation' | 'opacity', value: number) => update(selected.id, { [key]: value });
  return <aside className="w-[250px] shrink-0 border-l border-border bg-app-elevated p-4 hidden lg:block overflow-auto"><div className="flex items-center justify-between"><div><h2 className="text-xs uppercase tracking-wider text-muted">Element</h2><p className="text-sm font-medium mt-1 truncate max-w-[170px]">{selected.type}</p></div><Button size="icon" variant="danger" onClick={() => remove()} aria-label="Delete selected element"><Trash2 size={14} /></Button></div><div className="grid grid-cols-2 gap-2 mt-5"><NumberField label="X" value={selected.x} onChange={(value) => patch('x', value)} /><NumberField label="Y" value={selected.y} onChange={(value) => patch('y', value)} /><NumberField label="Width" value={selected.width} min={80} onChange={(value) => patch('width', value)} /><NumberField label="Height" value={selected.height} min={60} onChange={(value) => patch('height', value)} /></div><NumberField label="Rotation" value={selected.rotation} onChange={(value) => patch('rotation', value)} /><label className="block text-xs text-muted mt-3">Opacity<input type="range" min={0} max={100} value={selected.opacity} onChange={(event) => patch('opacity', Number(event.target.value))} className="mt-2 w-full accent-accent" /><span className="block text-right text-[11px] text-subtle">{selected.opacity}%</span></label><div className="mt-5 border-t border-border pt-4"><p className="text-xs text-muted mb-2">Layer order</p><div className="grid grid-cols-2 gap-2"><Button size="sm" onClick={() => changeLayer('front')}><Layers2 size={13} />Forward</Button><Button size="sm" onClick={() => changeLayer('backward')}>Backward</Button><Button size="sm" onClick={() => changeLayer('front')}>To front</Button><Button size="sm" onClick={() => changeLayer('back')}>To back</Button></div></div></aside>;
}

function NumberField({ label, value, onChange, min }: { label: string; value: number; onChange: (value: number) => void; min?: number }) { return <label className="block text-xs text-muted">{label}<input type="number" value={Math.round(value)} min={min} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 w-full h-8 rounded-lg border border-border bg-panel px-2 text-sm text-fg outline-none" /></label>; }
